spring:
  config:
    activate:
      on-profile: mek
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

product-config:
  amount-of-products-fetched-per-call: ${PRODUCTS_PER_CALL:10}

konfig:
  user: test
  password: test
  key: ${API_KEY}

fetchtask:
  cron: "*/5 * * * * *"
logging:
  level:
    jonk.mek.boascraper: debug