spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect

konfig:
  user: test
  password: test
  key: ${API_KEY}

fetchtask:
  cron: "*/5 * * * * *"
logging:
  level:
    jonk.mek.boascraper: debug