CREATE TABLE product (
    product_id VARCHAR(255) PRIMARY KEY,
    product_number VARCHAR(255),
    product_name_bold VARCHAR(255),
    product_name_thin VARCHAR(255),
    category VARCHAR(255),
    product_number_short VARCHAR(255),
    producer_name VARCHAR(255),
    supplier_name VARCHAR(255),
    is_kosher BOOLEAN,
    bottle_text VARCHAR(255),
    restricted_parcel_quantity INT,
    is_organic BOOLEAN,
    is_sustainable_choice BOOLEAN,
    is_climate_smart_packaging BOOLEAN,
    is_ethical BOOLEAN,
    ethical_label VARCHAR(255),
    is_web_launch BOOLEAN,
    product_launch_date TIMESTAMP,
    sell_start_time TIME,
    is_completely_out_of_stock BOOLEAN,
    is_temporary_out_of_stock BOOLEAN,
    alcohol_percentage DOUBLE PRECISION,
    volume_text VARCHAR(255),
    volume DOUBLE PRECISION,
    price DOUBLE PRECISION,
    country VARCHAR(255),
    origin_level1 VARCHAR(255),
    origin_level2 VARCHAR(255),
    category_level1 VARCHAR(255),
    category_level2 VARCHAR(255),
    category_level3 VARCHAR(255),
    category_level4 VARCHAR(255),
    custom_category_title VARCHAR(255),
    assortment_text VARCHAR(255),
    usage TEXT,
    taste TEXT,
    taste_symbols TEXT[],
    taste_clock_group_bitter INT,
    taste_clock_group_smokiness INT,
    taste_clock_bitter INT,
    taste_clock_fruitacid INT,
    taste_clock_body INT,
    taste_clock_roughness INT,
    taste_clock_sweetness INT,
    taste_clock_smokiness INT,
    taste_clock_casque INT,
    assortment VARCHAR(255),
    recycle_fee DOUBLE PRECISION,
    is_manufacturing_country BOOLEAN,
    is_regional_restricted BOOLEAN,
    packaging_level1 VARCHAR(255),
    is_news BOOLEAN,
    is_discontinued BOOLEAN,
    is_supplier_temporary_not_available BOOLEAN,
    sugar_content INT,
    sugar_content_gram_per_100ml DOUBLE PRECISION,
    seal VARCHAR(255)[],
    vintage VARCHAR(255),
    grapes VARCHAR(255)[],
    other_selections JSONB[],
    taste_clocks JSONB[],
    color VARCHAR(255),
    dish_points JSONB[]
);